# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('reading_type', models.CharField(choices=[('spectro', 'Spectrometer'), ('color', 'Color'), ('fluoro', 'Fluorescence')], default='spectro', max_length=32)),
                ('use_voice_memo', models.BooleanField()),
                ('use_photo', models.BooleanField()),
                ('post_capture_processing', models.CharField(choices=[('find_match', 'Search for a match'), ('check_limits', 'Compare to upper and lower limits'), ('none', 'No post capture processing')], default='find_match', max_length=32)),
                ('try_composite_candidates', models.BooleanField()),
                ('parent_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='GroupLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limits_exceeded_action', models.CharField(choices=[('send_email', 'Send email to group members'), ('take_another_reading', 'Take another reading'), ('none', 'take no action')], max_length=32)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
            options={
                'db_table': 'group_limit',
            },
        ),
        migrations.CreateModel(
            name='GroupMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id_of_reference_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_sample_group', to='api.Group')),
                ('group_id_of_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sample_group', to='api.Group')),
            ],
            options={
                'db_table': 'group_match_candidate',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('username', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('access_webapp', 'Access web application'), ('receive_notifications', 'Receive notifications'), ('take_samples', 'Take samples'), ('configure_group', 'Configure group')], max_length=32)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('histogram', 'Histogram')], max_length=32)),
                ('file_path', models.CharField(max_length=1024)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('datetime', models.FloatField()),
                ('number_of_satellites', models.IntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('reading_type', models.CharField(choices=[('spectro', 'Spectrometer'), ('color', 'Color'), ('fluoro', 'Fluorescence')], max_length=32)),
                ('record_type', models.CharField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual'), ('Defined', 'Derived')], max_length=32)),
                ('description', models.CharField(max_length=4096)),
                ('data', models.CharField(max_length=4096)),
                ('average_magnitude', models.IntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('representative_sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample')),
            ],
            options={
                'db_table': 'sample',
            },
        ),
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('magnitude', models.IntegerField()),
            ],
            options={
                'db_table': 'sample_data',
            },
        ),
        migrations.CreateModel(
            name='SampleDelta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=4096)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('reference_sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampledelta_reference_sample', to='api.Sample')),
                ('source_sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampledelta_source_sample', to='api.Sample')),
            ],
            options={
                'db_table': 'sample_delta',
            },
        ),
        migrations.CreateModel(
            name='SampleFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('peak', 'Peak'), ('valley', 'Valley'), ('spike', 'Spike'), ('hole', 'Hole'), ('plateau_start', 'Start of Plateau'), ('plateau_end', 'End of Plateau')], max_length=32)),
                ('frequency', models.IntegerField()),
                ('magnitude', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sample')),
            ],
            options={
                'db_table': 'sample_feature',
            },
        ),
        migrations.CreateModel(
            name='SampleMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0.0)),
                ('delta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SampleDelta')),
                ('reference_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplematch_reference_sample', to='api.Sample')),
                ('source_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplematch_source_sample', to='api.Sample')),
            ],
            options={
                'db_table': 'sample_match',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample')),
            ],
            options={
                'db_table': 'voice_memo',
            },
        ),
        migrations.AddField(
            model_name='sampledata',
            name='delta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SampleDelta'),
        ),
        migrations.AddField(
            model_name='sampledata',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='location',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AddField(
            model_name='image',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AddField(
            model_name='image',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='grouplimit',
            name='lower_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_limit', to='api.Sample'),
        ),
        migrations.AddField(
            model_name='grouplimit',
            name='upper_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_limit', to='api.Sample'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
    ]
