# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('histogram', 'Histogram'), ('bar_chart', 'Bar Chart')], max_length=32),
        ),
    ]
