# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160218_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='generate_chart',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
