# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20160209_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(default=234, on_delete=django.db.models.deletion.CASCADE, related_name='groupmember', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AddField(
            model_name='photo',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='grouplimit',
            name='lower_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_limit', to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='grouplimit',
            name='upper_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_limit', to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='location',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AlterField(
            model_name='location',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='representative_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='delta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SampleDelta'),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='sampledelta',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AlterField(
            model_name='sampledelta',
            name='reference_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampledelta_reference_sample', to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='sampledelta',
            name='source_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampledelta_source_sample', to='api.Sample'),
        ),
        migrations.AlterField(
            model_name='samplematch',
            name='delta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SampleDelta'),
        ),
        migrations.AlterField(
            model_name='voicememo',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sample'),
        ),
    ]
