# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160209_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='data',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
