# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sample_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
