# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160211_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
